// server/src/services/pdfService.ts

import PDFDocument from 'pdfkit';
import { Response } from 'express';
import { format } from 'date-fns';
import { PatientReportData, AppointmentReportData } from '../types';


// ============ PDF GENERATION FUNCTIONS ============

/**
 * Generate Patient Report PDF
 */
export const generatePatientReport = (data: PatientReportData, res: Response): void => {
    const doc = new PDFDocument({ margin: 50 });

    // Set response headers
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=patient-report-${format(new Date(), 'yyyy-MM-dd')}.pdf`);

    // Pipe to response
    doc.pipe(res);

    // Header
    doc
        .fontSize(24)
        .fillColor('#2563eb')
        .text('ClinicFlow', { align: 'center' })
        .fontSize(10)
        .fillColor('#666')
        .text('Medical Center', { align: 'center' })
        .moveDown();

    // Title
    doc
        .fontSize(18)
        .fillColor('#000')
        .text('Patient Report', { align: 'center' })
        .moveDown();

    // Report Info
    doc
        .fontSize(10)
        .fillColor('#666')
        .text(`Generated: ${format(data.generatedAt, 'PPpp')}`)
        .text(`Generated By: ${data.generatedBy}`)
        .text(`Total Patients: ${data.patients.length}`)
        .moveDown();

    // Table Header
    const tableTop = doc.y;
    const tableHeaders = ['Name', 'Age', 'Condition', 'Status', 'Registered'];
    const colWidths = [120, 50, 120, 80, 100];
    let xPos = 50;

    doc.fontSize(10).fillColor('#fff');
    
    // Header background
    doc.rect(50, tableTop, 470, 20).fill('#2563eb');
    
    // Header text
    doc.fillColor('#fff');
    tableHeaders.forEach((header, i) => {
        doc.text(header, xPos + 5, tableTop + 5, { width: colWidths[i] });
        xPos += colWidths[i];
    });

    // Table Rows
    let yPos = tableTop + 25;
    doc.fillColor('#000');

    data.patients.forEach((patient, index) => {
        if (yPos > 700) {
            doc.addPage();
            yPos = 50;
        }

        // Alternate row background
        if (index % 2 === 0) {
            doc.rect(50, yPos - 5, 470, 20).fill('#f8fafc');
        }

        xPos = 50;
        doc.fillColor('#000').fontSize(9);
        
        doc.text(patient.name, xPos + 5, yPos, { width: colWidths[0] });
        xPos += colWidths[0];
        
        doc.text(patient.age.toString(), xPos + 5, yPos, { width: colWidths[1] });
        xPos += colWidths[1];
        
        doc.text(patient.condition, xPos + 5, yPos, { width: colWidths[2] });
        xPos += colWidths[2];
        
        doc.text(patient.isAdmitted ? 'Admitted' : 'Outpatient', xPos + 5, yPos, { width: colWidths[3] });
        xPos += colWidths[3];
        
        doc.text(format(new Date(patient.createdAt), 'MMM d, yyyy'), xPos + 5, yPos, { width: colWidths[4] });

        yPos += 20;
    });

    // Footer
    doc
        .fontSize(8)
        .fillColor('#999')
        .text(
            'This is a computer-generated report. ClinicFlow Medical Center.',
            50,
            750,
            { align: 'center' }
        );

    doc.end();
};

/**
 * Generate Appointment Report PDF
 */
export const generateAppointmentReport = (data: AppointmentReportData, res: Response): void => {
    const doc = new PDFDocument({ margin: 50 });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=appointment-report-${format(new Date(), 'yyyy-MM-dd')}.pdf`);

    doc.pipe(res);

    // Header
    doc
        .fontSize(24)
        .fillColor('#2563eb')
        .text('ClinicFlow', { align: 'center' })
        .fontSize(10)
        .fillColor('#666')
        .text('Medical Center', { align: 'center' })
        .moveDown();

    // Title
    doc
        .fontSize(18)
        .fillColor('#000')
        .text('Appointment Report', { align: 'center' })
        .moveDown();

    // Report Info
    doc
        .fontSize(10)
        .fillColor('#666')
        .text(`Period: ${format(data.dateFrom, 'MMM d, yyyy')} - ${format(data.dateTo, 'MMM d, yyyy')}`)
        .text(`Generated: ${format(data.generatedAt, 'PPpp')}`)
        .text(`Total Appointments: ${data.appointments.length}`)
        .moveDown();

    // Summary Stats
    const statusCounts = data.appointments.reduce((acc, apt) => {
        acc[apt.status] = (acc[apt.status] || 0) + 1;
        return acc;
    }, {} as Record<string, number>);

    doc.fontSize(12).fillColor('#000').text('Summary:', { underline: true });
    Object.entries(statusCounts).forEach(([status, count]) => {
        doc.fontSize(10).text(`  ${status}: ${count}`);
    });
    doc.moveDown();

    // Table
    const tableTop = doc.y;
    const headers = ['Patient', 'Doctor', 'Date', 'Time', 'Status'];
    const colWidths = [100, 100, 90, 70, 80];
    let xPos = 50;

    doc.rect(50, tableTop, 440, 20).fill('#2563eb');
    doc.fillColor('#fff').fontSize(10);
    
    headers.forEach((header, i) => {
        doc.text(header, xPos + 5, tableTop + 5, { width: colWidths[i] });
        xPos += colWidths[i];
    });

    let yPos = tableTop + 25;
    doc.fillColor('#000');

    data.appointments.forEach((apt, index) => {
        if (yPos > 700) {
            doc.addPage();
            yPos = 50;
        }

        if (index % 2 === 0) {
            doc.rect(50, yPos - 5, 440, 20).fill('#f8fafc');
        }

        xPos = 50;
        doc.fillColor('#000').fontSize(9);
        
        doc.text(apt.patientName, xPos + 5, yPos, { width: colWidths[0] });
        xPos += colWidths[0];
        
        doc.text(`Dr. ${apt.doctorName}`, xPos + 5, yPos, { width: colWidths[1] });
        xPos += colWidths[1];
        
        doc.text(format(new Date(apt.date), 'MMM d, yyyy'), xPos + 5, yPos, { width: colWidths[2] });
        xPos += colWidths[2];
        
        doc.text(apt.timeSlot, xPos + 5, yPos, { width: colWidths[3] });
        xPos += colWidths[3];
        
        doc.text(apt.status, xPos + 5, yPos, { width: colWidths[4] });

        yPos += 20;
    });

    doc.end();
};